# Generated by Django 5.1.6 on 2025-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_pics/"
            ),
        ),
    ]
