# Generated by Django 5.1.6 on 2025-03-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_management", "__first__"),
        ("user_management", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bus_management.bus",
            ),
        ),
    ]
