# Generated by Django 5.0.2 on 2025-03-16 14:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bus_plate', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=255)),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='route_end_station_set', to='bus_management.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus_management.station')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='BusLog',
            fields=[
                ('log_id', models.CharField(default=uuid.uuid4, editable=False, max_length=5, primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('time_departed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('traffic_condition', models.CharField(choices=[('Light', 'Light'), ('Moderate', 'Moderate'), ('Heavy', 'Heavy')], max_length=255)),
                ('passenger_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus_management.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus_management.route')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus_management.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buslog_to_station_set', to='bus_management.station')),
            ],
            options={
                'db_table': 'bus_log',
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bus_management.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus_management.route')),
            ],
            options={
                'db_table': 'bus_route',
            },
        ),
        migrations.CreateModel(
            name='StationAssignment',
            fields=[
                ('station_assignment_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('station_order', models.IntegerField()),
                ('distance_to_next', models.FloatField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bus_management.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bus_management.station')),
            ],
            options={
                'db_table': 'station_assignment',
                'unique_together': {('route', 'station_order')},
            },
        ),
    ]
