# Generated by Django 5.1.6 on 2025-03-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bus_plate', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'bus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusLog',
            fields=[
                ('log_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('arrival_time', models.DateTimeField()),
                ('time_departed', models.DateTimeField()),
                ('traffic_condition', models.CharField(max_length=255)),
                ('passenger_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bus_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bus_management.bus')),
            ],
            options={
                'db_table': 'bus_route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationAssignment',
            fields=[
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bus_management.route')),
                ('station_order', models.IntegerField()),
                ('distance_to_next', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_assignment',
                'managed': False,
            },
        ),
    ]
